-- CREATE TABLE STUDENTS(
--     id INT PRIMARY KEY AUTO_INCREMENT,
--     first_name VARCHAR(20)
-- );
-- CREATE TABLE PAPERS(
--     title VARCHAR(50),
--     grade DECIMAL(4,2),
--     student_id INT,
--     Foreign Key (student_id) REFERENCES STUDENTS(id) ON DELETE CASCADE
-- );
-- INSERT INTO students (first_name) VALUES 
-- ('Caleb'), ('Samantha'), ('Raj'), ('Carlos'), ('Lisa');
-- INSERT INTO papers (student_id, title, grade ) VALUES
-- (1, 'My First Book Report', 60),
-- (1, 'My Second Book Report', 75),
-- (2, 'Russian Lit Through The Ages', 94),
-- (2, 'De Montaigne and The Art of The Essay', 98),
-- (4, 'Borges and Magical Realism', 89);
-- SELECT first_name,title,grade FROM students JOIN papers ON students.id=papers.student_id ORDER BY grade DESC;
-- SELECT first_name,title,grade FROM students LEFT JOIN papers ON students.id=papers.student_id;
-- SELECT first_name,IFNULL(title,'missing'),IFNULL(grade,0) FROM students LEFT JOIN papers ON students.id=papers.student_id;
-- SELECT first_name,IFNULL(AVG(grade),0) AS average FROM students LEFT JOIN papers ON student_id=id GROUP BY first_name ORDER BY average DESC;
-- SELECT
--     first_name,
--     IFNULL(AVG(grade), 0) AS average,
--     CASE
--         WHEN AVG(grade) >= 75 THEN 'PASSING'
--         ELSE 'FAILING'
--     END AS passing_status
-- FROM
--     students
--     LEFT JOIN papers ON student_id = id
-- GROUP BY
--     first_name
-- ORDER BY
--     average DESC;